---
title: "data211_final_project"
author: "LangeData211"
date: "2023-11-27"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
# Create a data frame 
Weight_LL_File <- data.frame(
  Date = c("10/3", "10/4", "10/5", "10/6", "10/7", "10/8", "10/9", "10/10", "10/11", "10/12", "10/13", "10/14", "10/15", "10/16", "10/17", "10/18", "10/19", "10/20", "10/21", "10/22", "10/23", "10/24", "10/25", "10/26", "10/27", "10/28", "10/29", "10/30", "10/31", "11/1", "11/2", "11/3", "11/4", "11/5", "11/6", "11/7", "11/8", "11/9", "11/10", "11/11", "11/12", "11/13", "11/14", "11/15", "11/16", "11/17", "11/18", "11/19", "11/20", "11/21"),
  Weight = c(216.2, 215.2, 216.8, 218.0, 219.0, 218.4, 217.8, 220.2, 221.4, 219.8, 219.4, 218.2, 218.0, 216.0, 215.6, 215.0, 219.8, 217.8, 216.0, 218.0, 218.2, 215.8, 214.8, 216.2, 216.4, 217.2, 218.0, 217.6, 219.2, 215.0, 214.2, 214.8, 216.0, 215.6, 216.0, 216.2, 216.4, 217.2, 216.2, 214.2, 215.2, 213.2, 214.0, 214.0, 214.8, 215.4, 214.4, 215.4, 217.4, 214.8),
  Pushups_40 = c("no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "no", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes", "yes")
)

```

## Run t-test
```{r}

# Split the data into two groups
group_no <- Weight_LL_File$Weight[Weight_LL_File$Pushups_40 == "no"]
group_yes <- Weight_LL_File$Weight[Weight_LL_File$Pushups_40 == "yes"]

#  t-test
t_test_result <- t.test(group_yes, group_no, alternative = "less")
names(t_test_result$estimate) <- c("mean of Pushups_yes", "mean of Pushup_no")

# Print the result
print(t_test_result)

# Conlclusion
# We reject the null hypothesis since the result p-value is below the observed
# p-value



```
## Creating a graph

```{r}
# Load ggplot2
library(ggplot2)
Weight_LL_File$Date <- as.Date(Weight_LL_File$Date, format = "%m/%d")

# Create the plot
ggplot(Weight_LL_File, aes(x=Date, y=Weight, color=Pushups_40)) +
  geom_line() + 
  geom_point() +
  labs(title="Weight Tracking Over Time",
       x="Date", y="Weight", color="Pushup Completed") +
  theme_minimal() +
  scale_color_manual(values = c("yes" = "blue", "no" = "red"))


```



